services:

  server:
    build:
      context: ../
      dockerfile: docker/Server.Dockerfile
    image: ghcr.io/gurkengewuerz/sshcontainer-server:latest
    restart: unless-stopped
    privileged: true
    ports:
      - "2222:2222"
    environment:
      - OAUTH_ENDPOINT=$OAUTH2_OAUTH_ENDPOINT
      - CLIENT_ID=$OAUTH2_CLIENT_ID
      - CLIENT_SECRET=$OAUTH2_CLIENT_SECRET
      - DOCKER_CAP_ADD=${DOCKER_CAP_ADD:-NET_ADMIN,NET_RAW}
      - DOCKER_IMAGE=${DOCKER_IMAGE:-ghcr.io/gurkengewuerz/sshcontainer-shell:main}
      - PARTITION_SIZE=${PARTITION_SIZE:-10GB}
      - QUOTA=${QUOTA:-1GB}
      - DOCKER_MEMORY_LIMIT=${DOCKER_MEMORY_LIMIT:-512M}
      - DOCKER_CPU_LIMIT=${DOCKER_CPU_LIMIT:-1.0}
      - DOCKER_READ_ONLY=${DOCKER_READ_ONLY:-false}
      - LOG_LEVEL=${LOG_LEVEL:-6}
      # Must match to the docker image
      - CONTAINER_CMD=${CONTAINER_CMD:-/wait-shell.sh,/bin/zsh}
      - CONTAINER_USER=${CONTAINER_USER:-user}
      - CONTAINER_VFS_MOUNT=${CONTAINER_VFS_MOUNT:-/workspace}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./data/server:/app"
      - "./data/vfs:/vfs"

  proxy:
    image: ubuntu/squid
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    volumes:
      - "./data/squid/squid.conf:/etc/squid/squid.conf"
